version: '3.8'

services:
  db:
    ports:
      - "5432:5432"  # Expose database port for development
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./database/dev-init.sql:/docker-entrypoint-initdb.d/dev-init.sql:ro

  backend:
    environment:
      - DEBUG=true
      - RELOAD=true
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    stdin_open: true
    tty: true

  frontend:
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - VITE_DEV_MODE=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev -- --host 0.0.0.0 --port 3000
    stdin_open: true
    tty: true

  # Development tools
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - dev-tools

volumes:
  redis_data:
    driver: local
